"""
Report Writing Tool
====================
Saves the final optimization report as a Markdown (.md) file
to the local outputs/ directory.
"""

import os
from datetime import datetime

from langchain_core.tools import tool

from config import OUTPUT_DIR
from logger import get_logger, log_tool_call

_logger = get_logger("ReportTools")


@tool
def write_optimization_report(
    title: str,
    content: str,
    priority: str = "MEDIUM",
) -> str:
    """Save an optimization report as a Markdown file to the local outputs directory.

    Creates a structured Markdown report with a header, metadata block,
    timestamp, priority level, and the provided content. The file is
    saved to the ``outputs/`` directory with a timestamped filename.

    Args:
        title:    Report title (e.g. "Q1 Assembly Line Optimization Plan").
        content:  The full body of the report in Markdown format.
        priority: Priority level — one of "LOW", "MEDIUM", "HIGH", or
                  "CRITICAL". Defaults to "MEDIUM".

    Returns:
        A confirmation string with the absolute path of the saved report,
        or an error message if the write fails.
    """
    try:
        os.makedirs(OUTPUT_DIR, exist_ok=True)

        timestamp = datetime.now()
        filename = (
            f"optimization_report_{timestamp.strftime('%Y%m%d_%H%M%S')}.md"
        )
        filepath = os.path.join(OUTPUT_DIR, filename)

        # Build the Markdown document
        report = f"""# {title}

---

| Field      | Value                                      |
|------------|--------------------------------------------|
| **Generated** | {timestamp.strftime('%Y-%m-%d %H:%M:%S')} |
| **Priority**  | {priority.upper()}                         |
| **System**    | Smart Factory MAS — Production Optimizer   |

---

{content}

---

> *This report was automatically generated by the Smart Factory Multi-Agent System.*
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)

        abs_path = os.path.abspath(filepath)
        success_msg = f"Report saved successfully to: {abs_path}"
        log_tool_call(
            _logger,
            "write_optimization_report",
            {"title": title, "priority": priority},
            success_msg,
        )
        return success_msg

    except Exception as e:
        error_msg = f"ERROR: Failed to write report — {type(e).__name__}: {e}"
        log_tool_call(
            _logger,
            "write_optimization_report",
            {"title": title, "priority": priority},
            error_msg,
        )
        return error_msg
